### ISSUE TITLE
Question about writing to a query

### ISSUE THREAD

**Issue by LydiaF** [NerdWalletOSS/apollo-invalidation-policies#22]
Hello again :)

I am struggling with using onWrite to a query that does not have a typename.

In the docs, the example for the employees query has a typename:

```js
ROOT_QUERY: {
        __typename: 'Query',
        employees: {
            __typename: 'EmployeesResponse',
            data: [{ __ref: 'Employee:1' }, { __ref: 'Employee:2' }]
        }
    },
```

However, in my cache, none of the queries have a typename like 'EmployeesResponse'. They look like this...
```js
ROOT_QUERY: {
        __typename: 'Query',
        tests: (4) [{…}, {…}, {…}, {…}]
```

Is it possible to write to the tests query above even though it does not have a typename? I thought maybe something like might work but 'hi' is not printing at all so I gave up :) 
```js
onWrite: {
    Query: ({ readField, modify }, { storeFieldName, parent }) => {
      console.log('hi', storeFieldName, parent)
    },
```

I feel like I am missing something obvious, thanks for any pointers!!

Lydia

**Comment by danReynolds** [comment]
Hey @LydiaF ! Because the invalidation policy events like onWrite use types to create the relationships, it works best to have your query responses be types vs arrays. We do this as best practice at our company in general for consistency as well as making queries easier to manage with type policies and links too.

If your query needs to be an array then you can use the '__default' handler like this:

'''
Typename: {
  onWrite: {
    __default: (actions, context) {}
  }
}
'''

But it would be easier to manage if it returned a type. Hope that helps! Let me know if you have further questions!

**Comment by LydiaF** [comment]
Hey @danReynolds :)

Thank you so much for your reply. I see that you are right... we are using hasura and are somewhat limited in this respect. There is an option for getting a type back from the query as you suggested. However there is currently no way to get types back for inserts and deletes. Seems like a good idea for a hasura feature though. 

In general may I just thank you and whoever made this x 1000. It is ridiculously helpful for deleting relationships. I was doing some overly funky stuff with apollo read function to deal with what I think are called dangling references.

Thank you!

**Comment by danReynolds** [comment]
Thanks! glad it's been helpful. Let us know if there are any features or things you'd appreciate
